action_server: 'Pose_ActionServer'
control_client: 'PositionJointInterface_trajectory_controller/follow_joint_trajectory'
planning_group: 'arm_exoscope'

# gains - proportional
kp: [10.0,10.0,10.0,50.0,50.0,50.0]

# control interval, in velocity control: rate at which rcm goals are sent, else: sets interval to execute incremental motion
dt: 0.01

# velocity scaling
alpha: 0.1

# link names
link: 'storz_exoscope_link_cm_optical'

# threshold, max velocity
th_t: 0.05
th_t_scale: [1.0, 1.0, 1.0, 0.005, 0.005, 0.005]
